kind: pipeline
name: production
steps:
- name: docker_cleanrl
  image: plugins/docker:17.12
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vwxyzjn/cleanrl
    dockerfile: cleanrl/experiments/docker/Dockerfile
    target: production
    auto_tag: true
- name: docker_cleanrl_nomad 
  image: plugins/docker:17.12
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: vwxyzjn/cleanrl_nomad
    dockerfile: cleanrl/experiments/docker/nomad.Dockerfile
    target: production
    auto_tag: true
